applicationPath: 'C:/Program Files/Microsoft Visual Studio/18/Community/Common7/IDE/devenv.exe'
stepDirectoryPath: 'C:/fla-ui-recorder'
stepName: 'test'
listAttacherConfig:
  - mainWindowTitle: 'Microsoft Visual Studio'
    bExactMatch: true
  - mainWindowTitle: 'Microsoft Visual Studio'
    bExactMatch: false